### ISSUE TITLE
More explication on the set-up please?

### ISSUE THREAD

**Issue by Naereen** [matchai/waka-box#10]
Hi,
Could you precise more the set-up, at the end, what does one have to do, after adding the environment variables?
Is it some code to run by yourself on your own laptop, every week?
Is it running somewhere on some cloud? Is it going to run by itself thanks to GitHub "actions" or something automatic like this?
Thanks for the details!
@Naereen

PS it looks very nice, good job :+1:

**Comment by matchai** [comment]
[GitHub Actions](https://github.com/features/actions) automatically runs waka-box on on the cloud as a [scheduled action](https://help.github.com/en/github/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule) at regular intervals. There should be no need to do anything else once the instructions have been followed. 👍
