### ISSUE TITLE
Support for total code stats badge from public profile

### ISSUE THREAD

**Issue by alanhamlett** [matchai/waka-box#102]
Requesting support for showing the badge shield from public profile pages, as seen here:

https://twitter.com/WakaTime/status/1444398541195988992

![FAuIre0UcAEXPuw](https://user-images.githubusercontent.com/522344/135738187-2cdc12f6-5dc0-477a-a22b-38c91574e879.png)

**Comment by matchai** [comment]
Closing this as outside of scope for this project
