### ISSUE TITLE
RangeError: Invalid count value Github Action Error

### ISSUE THREAD

**Issue by BackdevHong** [matchai/waka-box#124]
![how](https://user-images.githubusercontent.com/97325091/172295188-bedab54c-372e-4545-b51c-c1fa2b9f503b.png)
How to Fix it?

**Comment by abordage** [comment]
@[BackdevHong](https://github.com/BackdevHong), project is no longer maintained, apparently. Check [abordage/wakatime-box](https://github.com/abordage/wakatime-box)

**Comment by BackdevHong** [comment]
thanks
