### ISSUE TITLE
Workflow Failing

### ISSUE THREAD

**Issue by JamshedAlamQaderi** [matchai/waka-box#138]
When i forked this repo and changed everything as instructed. But when i ran the `scheduled` workflow below error is showing everytime

<img width="1059" alt="Screenshot 2023-08-07 at 6 03 43 PM" src="https://github.com/matchai/waka-box/assets/54829362/b550a8c6-6aab-4cd2-ad76-a1a70695b6f9">

This is my repo: https://github.com/JamshedAlamQaderi/waka-box

**Comment by Jessienka** [comment]
I got the same problem.....

**Comment by JamshedAlamQaderi** [comment]
I've found it works after the day I've been worked on. Let's say you've setup the workflow and plugin today and the workflow will be executed at 12:00 am and then it's gonna work

**Comment by JamshedAlamQaderi** [comment]
check my waka-box setup here: https://github.com/JamshedAlamQaderi/waka-box

**Comment by dengWuuu** [comment]
the same

**Comment by JamshedAlamQaderi** [comment]
@dengWuuu if your situation is same then issue will be solved after 12 AM

**Comment by dengWuuu** [comment]
> @dengWuuu if your situation is same then issue will be solved after 12 AM

yes！I find that
