### ISSUE TITLE
run failure: update-gist

### ISSUE THREAD

**Issue by liuhy99** [matchai/waka-box#144]
When I ran schedule.yml, I got this error: 
![image](https://github.com/matchai/waka-box/assets/170445568/7ca7cd35-ed7e-481c-b7e4-e7d0798173e1)
Has anyone encountered this error before? :worried: How did you solve it?

**Comment by jdfcc** [comment]
Looks like you should upgrade your node version and try again

**Comment by liuhy99** [comment]
> Looks like you should upgrade your node version and try again

Thank you! finally it works :joy:
