### ISSUE TITLE
Forked repo doesn't trigger action

### ISSUE THREAD

**Issue by MarchWorks** [matchai/waka-box#19]
Add this to readme https://github.community/t5/GitHub-Actions/Forked-repo-doesn-t-trigger-action/m-p/32575#M1189

**Comment by MarchWorks** [comment]
@coord-e I think that you have this problem I solved it with the above workaround.

**Comment by coord-e** [comment]
@MarchWorks I could get my fork worked with that workaround. Thanks!

**Comment by imbsky** [comment]
This should work on fork without any workaround now.
