### ISSUE TITLE
Increase number of languages

### ISSUE THREAD

**Issue by montogeek** [matchai/waka-box#20]
Hello!

Have you tinker with the idea of increasing or make it possible to have dynamic number of programming languages?

5 is small, from Wakatime leaderboards in average each developer works in 8~10 different programming languages.

I can PR it.

**Comment by seognil** [comment]
I think so

I updated the schedule to run on push,
Simply modified the index.js (change gist title) and run build, but gist not changing
Is there something else that needs to be done?

**Comment by WincerChan** [comment]
same to me.
I changed index.js and run command 'npm run-scripts build', but it still display top 5.
