### ISSUE TITLE
Too big names

### ISSUE THREAD

**Issue by Akionka** [matchai/waka-box#25]
If programming language is too big, it would cause that bug

![Screenshot_2020-01-06-13-10-27-696_com android chrome](https://user-images.githubusercontent.com/42269025/71811506-f193cb80-3085-11ea-93ea-7db141862ec2.png)

**Comment by SASUKE40** [comment]
![image](https://user-images.githubusercontent.com/3114495/84615278-2b9daf00-aefb-11ea-9c9b-d056df36d742.png)
I meet the same problem. It seems to be a trouble for fixing.

**Comment by matchai** [comment]
Closed as fixed in #81.
