### ISSUE TITLE
Update gist error with "null" data 

### ISSUE THREAD

**Issue by xiaozhaoqi** [matchai/waka-box#28]
It's a good tool and help me record programming.
But, if there has not any record at the past week, the waka-box Action will throw a error, just like: 
`HttpError: Validation Failed: {"resource":"Gist","code":"missing_field","field":"files"}`  

![image](https://user-images.githubusercontent.com/22343967/73191248-231e2500-4162-11ea-960f-c24cbfd759a3.png)  

It caused a empty gist, and the pinned waka-box displayed empty.

**Comment by conv1d** [comment]
I also encountered this problem.
If array `lines` is empty, then the content of new gist will be empty, which is not allowed.
So it's necessary to add some processing for the case of empty array.
