### ISSUE TITLE
Formatting for long languages

### ISSUE THREAD

**Issue by HofmannZ** [matchai/waka-box#43]
The formatting for long languages seems off. See my gist: https://github.com/HofmannZ 

The name `Protocol Buffers` is misaligning the percentage bar.

**Comment by lucasvazq** [comment]
Same issue here 
![2020-06-28-180859_760x144_scrot](https://user-images.githubusercontent.com/38964964/85958240-75aa7a00-b96a-11ea-9ffa-16aa1f9da8f3.png)

**Comment by Hephaest** [comment]
Same issue here
![Screenshot (8)](https://user-images.githubusercontent.com/37981444/103721767-7bfc6b80-5009-11eb-8d58-4977576a2bc1.png)

**Comment by matchai** [comment]
Closed as fixed in #81.
