### ISSUE TITLE
Can't update gist

### ISSUE THREAD

**Issue by abhisheknaiidu** [matchai/waka-box#46]
Getting this same `error` every time

<img width="1213" alt="Screenshot 2020-06-19 at 2 47 27 PM" src="https://user-images.githubusercontent.com/55599878/85119578-9d4d6400-b23f-11ea-956c-0ca0298c055d.png">

My gist looks like this,

<img width="1213" alt="Screenshot 2020-06-19 at 3 15 15 PM" src="https://user-images.githubusercontent.com/55599878/85119665-ba823280-b23f-11ea-959f-1072f971c885.png">

**Comment by abhisheknaiidu** [comment]
@matchai @MarchWorks

**Comment by abhisheknaiidu** [comment]
Closing this, as it was fixed!

**Comment by ZainZh** [comment]
> Closing this, as it was fixed!

Hi, how did you fix this?
