### ISSUE TITLE
How much time it takes to appear for 1st time

### ISSUE THREAD

**Issue by 1UC1F3R616** [matchai/waka-box#53]
- I have followed all the steps but I am not getting it displayed
- I read that you are using only 1 commit so I think maybe it's because of your cron job timing

Below is the image of what It's showing me in gists | My github pinned gist is shown empty

![image](https://user-images.githubusercontent.com/41824020/87247638-b29a6480-c472-11ea-802e-cc304e098d2e.png)

**Comment by 1UC1F3R616** [comment]
If there's a possible error then please let me know

**Comment by ukyzr** [comment]
the actions not at all to run so there not have file to show, you need to delete original schedule.yml and create a new to push again.
