### ISSUE TITLE
Getting **We couldn’t find that file to show. **

### ISSUE THREAD

**Issue by 1UC1F3R616** [matchai/waka-box#54]
![image](https://user-images.githubusercontent.com/41824020/87254006-e38f8f00-c49c-11ea-8113-60bb52bdbfbd.png)

**Comment by 1UC1F3R616** [comment]
Above image is shown in my gist, I followed all procedures

**Comment by 1UC1F3R616** [comment]
I found that my github actions are not running...
I have no particular idea what to be done with this, help needed

**Comment by 1UC1F3R616** [comment]
![image](https://user-images.githubusercontent.com/41824020/87254146-11290800-c49e-11ea-9f8e-96255716b84c.png)

**Comment by ukyzr** [comment]
first, you need to update your schedule.yml and push again
