### ISSUE TITLE
Unable to get gist to update... Requesting help. 

### ISSUE THREAD

**Issue by rlam3** [matchai/waka-box#78]
```

Run matchai/waka-box@master
(node:2499) UnhandledPromiseRejectionWarning: Error: Request failed with status code 401
    at createError (/home/runner/work/_actions/matchai/waka-box/master/dist/index.js:372:15)
    at settle (/home/runner/work/_actions/matchai/waka-box/master/dist/index.js:6118:11)
    at IncomingMessage.handleStreamEnd (/home/runner/work/_actions/matchai/waka-box/master/dist/index.js:7018:15)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:2499) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2499) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

My waka-box repo: https://github.com/rlam3/waka-box
GIST: https://gist.github.com/rlam3/f66b68a6bcd096a4f732e1e4c2e16323

I did notice that we needed to create an environment before we can add secrets. Was there a specific name we had to give this property? I use 'master' as my environment. 

@matchai 

I'm receiving the following error. Where do I begin to debug? Thanks!

**Comment by Hephaest** [comment]
Man, I found that you gist has successfully updated in 2 hours ago. Is this issue still occur? Or else you can close this issue.

**Comment by zhuo1angT** [comment]
I've come across the same problem, the reason is that the secret hadn't been properly set.

**Comment by rlam3** [comment]
@zhuo1angT Yes. this was the problem. I have also pushed out a new write up on this as well. 
https://github.com/rlam3/waka-box

**Comment by rlam3** [comment]
I have also created a pull request to detail out how to better setup the secrets. 

https://github.com/matchai/waka-box/pull/84

**Comment by peterroe** [comment]
> I have also created a pull request to detail out how to better setup the secrets.
> 
> #84

您好，我需要你的帮助，我scrects两个都配置了，但还是无法解决上面的错误

**Comment by uhr** [comment]
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/3774016/153981202-c09e8691-9324-47e9-950a-b6e2d07e28d8.png">

I also encountered this problem, and found the secret key was put in the wrong place.
