### ISSUE TITLE
gist not update

### ISSUE THREAD

**Issue by kuhsinyv** [matchai/waka-box#85]
may be waka box action not runing？
![68A03DC7-BA7B-4D84-81BC-B178EB3957F4](https://user-images.githubusercontent.com/55936729/110470194-858f7600-8115-11eb-914e-f461d6c7ba0a.png)

**Comment by xymeng16** [comment]
Hello, did you fix this problem? I met the same one.

**Comment by UltiRequiem** [comment]
Me too

**Comment by xymeng16** [comment]
> Me too, any idea @xymeng16 ?

Move the .github directory out, commit and push, then move it back, commit and push again. I solved the problem by such operations. Seems Github has some difficulty recognizing the forked repo which includes github actions.

**Comment by UltiRequiem** [comment]
> > Me too, any idea @xymeng16 ?
> 
> Move the .github directory out, commit and push, then move it back, commit and push again. I solved the problem by such operations. Seems Github has some difficulty recognizing the forked repo which includes github actions.

Thanks!
